### ISSUE TITLE
z(...).unformat is not a function

### ISSUE THREAD

**Issue by andry89** [xsanisty/jquery-calx#48]
Hi,

My application has always worked correctly. From today I find this console error "z (...). Unformat is not a function".
Could you give me some indication to go back to the cause?

thank you

**Comment by ikhsan017** [comment]
Hi @andry89

Can you provide detailed stack trace?

**Comment by andry89** [comment]
Hi @ikhsan017 

I just solved the malfunction, using a previous version of numeral.js

With calx.2.0.6 and numeral.2.0.4, it does not work
With calx.2.0.6 and numeral.1.4.5 works

**Comment by macsupport** [comment]
Still an issue when using numeral v2.06 (newest). Works fine with v1.56.

**Comment by redmagi** [comment]
numeral js remove unformat function in version 2 [2.0](https://github.com/adamwdraper/Numeral-js#200)
i fixed by used numeral js version 1.5.6
