### ISSUE TITLE
Sheet is not defined

### ISSUE THREAD

**Issue by vguenichon** [xsanisty/jquery-calx#15]
Hi,
I try to take advantage of the keyboard to navigate through the fields. But I have a problem. There's an error "sheet is not defined".
Here is the code (from my page https://www.fluidtopics.com/roi-2/) :
```javascript
jQuery('#roi').on('keydown', 'input', function(e) {
    var self = jQuery(this)
      , form = self.parents('form:eq(0)')
      , focusable
      , next
      ;
    if (e.keyCode == 13) {
        console.log("enter pressed");
        jQuery(".roiquestion:visible").toggle("slide", { direction: "left" }, 300, function(){
            jQuery(this).next(".roiquestion").toggle("slide", { direction: "right" }, 300);
        });
        focusable = form.find('input').filter(':visible');
        console.log(focusable);
        next = focusable.eq(focusable.index(this)+1);
        if (next.length) {
            next.focus();
        } else {
            sheet.calculate();
            jQuery(".roiquestions").fadeOut(function(){
                jQuery(".roiresult").delay(400).fadeIn();
            });
        }
        return false;
    }
});
```
Thanks a lot for your help !
PS : I'm working with the 2.0.5 version as this code doesn't work at all with the last revision.

**Comment by ikhsan017** [comment]
Hi @vguenichon 

you should get the sheet object first, since you apply jQuery event handler instead of calx event, based on your code, you can do 

```javascript
var sheet = self.calx('getSheet');
```

**Comment by vguenichon** [comment]
Thanks a lot for your help.
I inserted this line before `sheet.calculate();` but now there's another error : `sheet.calculate is not a function`. Really ? I thought it was ;-)

**Comment by ikhsan017** [comment]
Errr, sorry its my bad

it should ```var sheet = jQuery('#roi').calx('getSheet');```

**Comment by vguenichon** [comment]
No it's mine... ;-) I don't know why I didn't see this before ! Thanks a lot.
Another tjing : I saw there's a new version (2.2.2) with a different approach for calculation. Do you think it would be a big deal to switch to this version from 2.0.5 ?

**Comment by ikhsan017** [comment]
it should be no problem to just replace the 2.0.5 with 2.2.2, since it is on same 2.x release

**Comment by vguenichon** [comment]
Thanks a lot !
